# Generated by Django 4.2.8 on 2023-12-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField(auto_now=True)),
                ('author', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
