# Generated by Django 4.2.5 on 2023-12-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='books2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField(auto_now=True)),
                ('author', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
