# Generated by Django 4.2.8 on 2023-12-11 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_books_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='myapp.books_price'),
            preserve_default=False,
        ),
    ]
